CREATE SEQUENCE SEQ_ACIDENTE
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TB_ACIDENTE (
    ACIDENTE_ID INTEGER DEFAULT SEQ_ACIDENTE.NEXTVAL NOT NULL,
    MODELO_VEICULO VARCHAR2(100) NOT NULL,
    PLACA_VEICULO VARCHAR2(10) NOT NULL,
    DATA_OCORRENCIA DATE NOT NULL,
    ENDERECO VARCHAR2(100) NOT NULL
);